### ISSUE TITLE
Why not use Flask[async]?

### ISSUE THREAD

**Issue by Lvl4Sword** [CryptocurrencyExplorer/CryptocurrencyExplorer#14]
Because it requires Python 3.7, which can't be expected from anyone using something like Ubuntu 18.04 which has 3.6.9

**Comment by dermoth** [comment]
I mentioned it in the chat but for the records - I think you should try installing 3.7+ (it can be installed from ppa:deadsnakes/ppa - see https://ubuntuhandbook.org/index.php/2020/07/python-3-8-4-released-install-ubuntu-18-04-16-04/) You can actually pick 3.7 to 3.9... (I'm using 3.7, so if you picked 3.8/3.9 it could have better version coverage...)

I'm not very familiar with async, but I hate to see technical decisions be taken based on obsolete software, and if async makes sense we should probably be using it form the start (and I need to learn it anyway).

There is even an async rpc library for bitcoin, and of course zeromq also do async (if we integrate with it.... it could also help make non-async bits work with an async core...)

**Comment by Lvl4Sword** [comment]
Ubuntu 20.04 will be the minimum required starting in January, so I'll play with Flask[async] then.
