### ISSUE TITLE
Setup Caching

### ISSUE THREAD

**Issue by Lvl4Sword** [CryptocurrencyExplorer/CryptocurrencyExplorer#16]
https://flask-caching.readthedocs.io/en/latest/

**Comment by dermoth** [comment]
+1 - ideally we should at least have local (in-memory/shm) and external cache available as config options (ex memcached or redis... I used both and my preference is for memcached for its simplicity/speed, but redis could enable other use cases).

The external cache option is important for larger sites that may have many reader backends and need a shared cache cluster across all of them for better efficiency.

**Comment by Lvl4Sword** [comment]
Each attempt of trying to use .memoize() or .cache() through Flask-Caching, seems to destroy anything to do with pagination.
This is most obvious with addresses, but can be seen on the front page as well.

I might be messing something up, but it's 100% tied to caching because after the decorators were removed, no more issues.

**Comment by Lvl4Sword** [comment]
https://github.com/CryptocurrencyExplorer/CryptocurrencyExplorer/commit/55ee31d31e80c41c5c1ec70ace1c07b71bac0985 handles this
