### ISSUE TITLE
Catch psycopg2.errors.UniqueViolation in cronjob.py / first_run.py

### ISSUE THREAD

**Issue by Lvl4Sword** [CryptocurrencyExplorer/CryptocurrencyExplorer#18]
Caught an edge case with this in cronjob.
To fix this, the latest height in every table should be deleted to handle this and move on.

**Comment by dermoth** [comment]
Do you still have the exact error message?

Ideally the db should handle forks nicely, so if going back and forth between two competing forks we don't have to reimport all blocks for the new winning fork... This means you can have more than one blocks for a given height, and it's not limited to the last block only (imho, it could even be an option to keep forks, although it would be pretty hard to guarantee all forks were captures unless you run a vast network of nodes, else a cleanup tool could allow deleting obsolete blocks)

**Comment by Lvl4Sword** [comment]
I don't have the exact error message right now but if I bump into it again I'll share it.
But it looks like it hung up on the latest commit attempt. The logic in my head is that removing the latest height in all tables will fix this.

**Comment by Lvl4Sword** [comment]
This is taken care of in a WIP commit via ``from sqlalchemy.exc import IntegrityError`` wrapping ``lets_boogy`` in ``first_run``.

```py
except IntegrityError:
    db.session.rollback()
```
is the magic here.

Huzzah!

**Comment by Lvl4Sword** [comment]
Look like this is also tied to the cronjob.py running in some capacity while first_run.py is also running. Looks to be a race condition where first_run sees a block/address/etc, cronjob does something, and then when first_run tries to commit, it fails.

I know this because bringing up a test server bumped into this exact scenario :+1:
