### ISSUE TITLE
Have the option to parse the block files rather than rpc

### ISSUE THREAD

**Issue by Lvl4Sword** [CryptocurrencyExplorer/CryptocurrencyExplorer#23]
This isn't for 1.0, but would be nice to have down the road.

**Comment by dermoth** [comment]
IMHO a good rpc loader should be as fast as block parser if not faster... Blocks are not always ordered too which makes it quite complex (you have to support importing blocks and transactions out of order and linking them after. You will also be loading duplicate blocks, which may or may not be desired (depending if you support chain forks or not...)

In any case I think think my idea for separating the rpc and loader parts with some communication mechanism (ex zeromq) would be helpful here too - you could write a standalone block parser that provdes the same interface to the client. You would probably have to parse/index headers first, so the client can request blocks, but this way you can load them in order and also load forks.

**Comment by Lvl4Sword** [comment]
I don't feel this is necessary or needed. The concept of the explorer is to make it as easily as possible.
It's up to the underlying mechanism doing RPC/block loading to do this, not this project.
