### ISSUE TITLE
Catch BrokenPipeError: [Errno 32] Broken pipe in python-bitcoinrpc

### ISSUE THREAD

**Issue by Lvl4Sword** [CryptocurrencyExplorer/CryptocurrencyExplorer#27]
If python-bitcoinrpc needs to be forked, I'm fine with that.
This didn't spring up before so am unsure why it's showing up now. But regardless is a good idea to catch.

**Comment by dermoth** [comment]
Do you have the full backtrace? You probably need to handle reconnections - for most libraries that is normally done by the client... This is one of the reasons I suggested separating the bits though - have a separate process to read the blocks then send them to a import process using lightweight ipc (ex ZeroMQ). This also allow reading as fast as possible without being blocked by the database import, and making block reader fairly easy to replace.

**Comment by Lvl4Sword** [comment]
Using ~~``requests``~~ ``requests.Session`` looks to be the better idea here. I'll close this when that's implemented.
