### ISSUE TITLE
ERROR in first_run: Doesn't look like you have the daemon running. Fix this

### ISSUE THREAD

**Issue by Q7xB12** [CryptocurrencyExplorer/CryptocurrencyExplorer#40]
im getting this error whenever I attempt to run the first run': ERROR in first_run: Doesn't look like you have the daemon running. Fix this
and it doesn't matter if daemon running or not keep getting this error.
Any assistance would be greatly appreciated. Thank you in advance.

**Comment by Lvl4Sword** [comment]
Which coin are you using? How are you running it?

**Comment by Lvl4Sword** [comment]
Never got a response to this, so closed it.
@Q7xB12 If you still have the issue, respond to this so it can get looked into. Otherwise, this will be considered a non-issue.
